---
title: "paper1 v2"
output: html_document
date: "2022-08-10"
---


```{r}
source("utils.R")
source("notebook_utils.R")# load in utility functions
require(tidyr)
# for presentation.
require(ggfortify)
require(Hmisc)
# for missingness.
require(tidyr)
require(VIM)
require(mice)
require(lattice) # for histogram.
require(laeken) # for weighedMean.
# for extrapolation.
require(tidyr)
# for heterogeneity.
require(tidyr)
require(glmnet)
require(geepack)
require(lme4)
require(MuMIn)
library(jtools) # for forest plots
library(ggstance) # needed for jtools but not a dependency ..
library(sandwich)
library(sjPlot) # forest plots
library(ggplot2) # ggplot
library(ggpattern) # patterened kdes
library(texreg) # model outputs to tex tables. 
library(strucchange) # CHOW TEST
library(car) # levene test
```

```{r}
data <- format_transition_data("../data/raw_US/", c(2011,2012, 2013), "SF.12")

pdf("../plots/total_missingness_structure.pdf")
aggr(subset(data, select=-c(y)), sortVars=T,  oma=c(8,4,4,4), numbers=T, cex.axis=1.0, col = c(blue, orange), prop=F, combined=T, cex.numbers=0.5)
dev.off()

data <- data[complete.cases(data),]
data$ethnicity <- relevel(factor(data$ethnicity), ref="WBI")
data$education_state <- relevel(factor(data$education_state), ref="GCSE")
data$region <- relevel(factor(data$region), ref="London")
data$sex <- factor(data$sex)
data$labour_state <- factor(data$labour_state)
data$job_sec <- factor(data$job_sec)
data$gross_hh_income <- scale(data$gross_hh_income)
data$age <- scale(data$age)

sf12.lm <- lm(y ~ sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec +
               region +
               gross_hh_income,
               data= data)
a<- summary(sf12.lm)
print(a)
print(a$adj.r.squared)

pdf("../plots/ols_residuals.pdf")
hist(scale(a$residuals), ylab = "Density", breaks = 100, freq=F, main = '', xlab = 'SF12 Scaled Residuals')
lines(seq(-4, 4, 1/1000), dnorm(seq(-4, 4, 1/1000)), col='red', lty=2)
legend('topleft', col='red', lty=2, legend=c('Standard Normal'))
dev.off()

#pdf("../plots/ols_forest_plot.pdf")
#plot_summs(sf12.lm)
#dev.off()

pdf("../plots/ols_forest_plot.pdf")
plot_models(sf12.lm, p.shape=T, legend.title = NULL, m.labels=NULL)
dev.off()
```

# Presentation
Show how better presentation of 
- histogram of actual vs regression
- autoplot leverage plots.

```{r}

hist(scale(sf12.lm$residuals), col = blue)
hist(scale(data$SF.12), col=orange, add=T)

hist(scale(sf12.lm$residuals), col = blue, alpha=0.7)
hist(scale(data$SF.12), col=orange, add=T, alpha=0.7)
legend('topleft', legend=c("Predicted", "Actual"), col=c(blue, orange), lty=1)

res <- as.data.frame(sf12.lm$fitted)
real <- as.data.frame(data$SF.12)
res$type <- c("Predicted")
real$type <- c("Real")
colnames(res) <- c("SF12", 'type')
colnames(real) <- c("SF12", 'type')
hist.data <- rbind(res,real)

ols.hist <- ggplot(hist.data, aes(x=SF12, fill = type, col=type)) +
  geom_histogram(aes(y=..density..), alpha=0.5, binwidth=2, position='identity')

ols.densities <- ggplot(hist.data) +
  geom_density_pattern(aes(x=SF12, pattern_fill = as.factor(type), pattern_type = as.factor(type)),
                       alpha=0.1,
                  pattern = 'polygon_tiling',
                   pattern_key_scale_factor = 1.2,
                  pattern_alpha=0.4)+        
  scale_pattern_type_manual(values = c("hexagonal", "rhombille"))+
       theme_bw(18) +
       theme(legend.key.size = unit(2, 'cm'))
pdf("../plots/ols_densities.pdf")
ols.densities
dev.off()

pdf("../plots/ols_fitted_residuals.pdf")
plot(sf12.lm, 3)
dev.off()

pdf("../plots/ols_sf12_leverage.pdf")
plot(sf12.lm, 5)
dev.off()

texreg(summary(sf12.lm), dcolumn=T, booktabs=T, file='ols_output.txt', title="SF12 OLS Coefficients", custom.model.names=c("SF12 OLS"), single.row=T, include.aic=T)

```



# Missingness
```{r}
data <- format_transition_data("../data/corrected_US/", c(2011,2012, 2013), "SF.12")
pdf("../plots/total_missingness_structure2.pdf")
aggr(subset(data, select=-c(y)), sortVars=T,  oma=c(8,4,4,4), numbers=T, cex.axis=1.0, col = c(blue, orange), prop=F, combined=T, cex.numbers=0.5)
dev.off()

pdf("../plots/ethnicity_SF12_spinogram.pdf")
spineMiss(data[, c("ethnicity", "SF.12")], col = c(blue, orange))
dev.off()

pdf("../plots/labour_SF12_spinogram.pdf")
spineMiss(data[, c("labour_state", "SF.12")], col = c(blue, orange))
dev.off()

is_missing_sf12 <- is.na(data$y)
pdf("../plots/age_SF12_histograms.pdf")
histogram(~age|is_missing_sf12, data)
dev.off()
```


```{r}
imp_columns <- c("y",
                  "sex",
                  "ethnicity", 
                  "age",
                  "education_state",
                  "labour_state",
                  "job_sec",
                  "region",
                  "gross_hh_income",
                  "SF.12")
data$job_sec <- factor(data$job_sec)
mice_set <- mice(data = data[,imp_columns],
                 m = 10, maxit = 10,
                 remove.collinear=T)

pdf("../plots/ols_mice_convergence.pdf")
plot(mice_set)
dev.off()

```


SF.12 pooled regression
```{r}
mice.sf12.lm <- with(mice_set, lm(y ~ sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec +
               region +
               gross_hh_income))
final.pool<- pool(mice.sf12.lm)


pooled_lm = mice.sf12.lm$analyses[[1]]
pool.sum <- summary(final.pool)
pooled_lm$coefficients = pool.sum$estimate
mice.preds<- predict(pooled_lm, data)

pool.r.squared(final.pool)

# mice objects dont go in forest plot annoyingly. move coefficients over to a
# dummy lm that plot_models can read.
mice.lm.object <- summary(lm(y ~ sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               factor(job_sec) +
               region +
               gross_hh_income, data = data))
mice.lm.object$coefficients[,1] <- pool.sum$estimate
mice.lm.object$coefficients[,2] <- pool.sum$std.error
mice.lm.object$coefficients[,3] <- pool.sum$statistic
mice.lm.object$coefficients[,4] <- pool.sum$p.value

texreg(mice.lm.object, dcolumn=T, booktabs=T, file='../plots/mice_ols_coefficients.txt', title="SF12 MICE OLS Coefficients", custom.model.names=c("SF12 OLS"), single.row=T, include.aic=T)

pdf("../plots/mice_imputed_OLS_forest.pdf")
plot_models(mice.lm.object, p.shape=T, legend.title = NULL, m.labels=NULL)
dev.off()

pdf("../plots/SF12_MICE_comparison_histogram.pdf")
hist(data$SF.12, col = t_blue, border = blue, freq=F, ylim = c(0, 0.05))
hist(mice.preds, col = t_orange, border = orange, freq=F, add = T)
legend("topright", c("Complete", "Imputed"), fill=c(blue, orange))
dev.off()


#pdf("../plots/MICE_depression_scatter.pdf")
#plot_depression_residuals(mice.preds, test$SF.12)
#dev.off()

res <- as.data.frame(predict(pooled_lm,data))
real <- as.data.frame(data$SF.12)
res$type <- c("Predicted")
real$type <- c("Real")
colnames(res) <- c("SF12", 'type')
colnames(real) <- c("SF12", 'type')
hist.data <- rbind(res,real)

ols.hist <- ggplot(hist.data, aes(x=SF12, fill = type, col=type)) +
  geom_histogram(aes(y=..density..), alpha=0.5, binwidth=2, position='identity')

mice.ols.densities <- ggplot(hist.data) +
  geom_density_pattern(aes(x=SF12, pattern_fill = as.factor(type), pattern_type = as.factor(type)),
                       alpha=0.1,
                  pattern = 'polygon_tiling',
                   pattern_key_scale_factor = 1.2,
                  pattern_alpha=0.4)+        
  scale_pattern_type_manual(values = c("hexagonal", "rhombille"))+
       theme_bw(18) +
       theme(legend.key.size = unit(2, 'cm'))

pdf('../plots/mice_ols_densities.pdf')
mice.ols.densities
dev.off()
```



# Extrapolation

chow test over time.
lasso
any weighted regression if possible. 
```{r}
# chow test
sctest(y ~ time, data=data, type='Chow', point=10)
data2 <- complete(mice_set)
data2$pidp <- data$pidp
data2$time <- data$time

sctest(y ~ (factor(sex) + 
               factor(ethnicity) + 
               age + 
               factor(education_state) + 
               factor(labour_state) + 
               factor(job_sec) +
               factor(region) +
               gross_hh_income), type='Chow', data = data2)
# negative p=value suggests structural change in data.
```
```{r}
# lasso

x <- model.matrix(y ~ factor(sex) + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec +
               region +
               gross_hh_income,
               data=data2)

y <- data[complete.cases(data2), ]$y

# Fit LASSO
cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "gaussian")
lasso <- glmnet(x, y, alpha = 1, family = "gaussian", lambda=cv.lasso$lambda.1se)


pdf('../plots/ols_lasso.pdf')
plot(lasso, xvar = "lambda", label = T) 
abline(v = log(cv.lasso$lambda.min), col = "blue",lty=2)
abline(v = log(cv.lasso$lambda.1se), col = "red", lty=3)
legend('bottomright', legend=c("Minimum Standard Error", "First Standard Error"), col=c('blue', 'red'), lty=c(2, 3))dev.off()

pdf('../plots/ols_cv_lasso.pdf')
plot(cv.lasso)
dev.off()

coef(cv.lasso, s = "lambda.min")

#best.min<- glmnet(x2, y2, alpha=1, family = "gaussian", lambda = cv.lasso$lambda.min)
#best.1se<- glmnet(x2, y2, alpha=0.5, family = "gaussian", lambda = cv.lasso$lambda.1se)

# note the type = "class" is preferable here. 
# the choice of a cutoff at p=0.5 is very arbitrary and this function helps
# to optimise the position of that line.
```

```{r}
# reweighting. 

# extrapolation through reweighting if possible..
```

# Heterogeneity

tests of heterogeneity levene. residual fitted.
gee with previous term
gee
glmm
glmm gamma

```{r}
 leveneTest(y~factor(time), data=data)

```

```{r}


sf12.lm.oneterm <- lm(y  ~  sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec + 
               scale(gross_hh_income) +  
               SF.12, data=data2)


pdf("../plots/ols_oneterm_densities.pdf")
compare_densities_plot(predict(sf12.lm.oneterm), data2$y, "SF.12")
dev.off()

dep.gee <- geeglm(y ~ sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec + 
               scale(gross_hh_income) + SF.12 + 1:pidp , data = data2[complete.cases(data2),], family = gaussian,id=pidp
              , corstr="ar1")

gee.preds <- predict(dep.gee, data2)
pdf("../plots/gee_densities.pdf")
compare_densities_plot(gee.preds, data2$y, "SF.12")
dev.off()
print(summary(dep.gee))
print(QIC(dep.gee))

```

```{r}
dep.glmm <- lmer(y  ~  sex + 
               ethnicity + 
               age + 
               education_state + 
               labour_state + 
               job_sec + 
               scale(gross_hh_income) +
                (1|pidp), data = data2[complete.cases(data2),])


glmm.sum <- summary(dep.glmm)
AIC(dep.glmm)
r.squaredGLMM(dep.glmm)

glmm.preds <- predict(dep.glmm)
pdf("../plots/glmm_densities.pdf")
compare_densities_plot(glmm.preds, data2$y, "SF.12")
dev.off()

dep.glmm.gamma <- glmer(y+0.0001  ~  factor(sex) + 
               factor(ethnicity) + 
               age + 
               factor(education_state) + 
               factor(labour_state) + 
               factor(job_sec) + 
               scale(gross_hh_income) +
                (1|pidp),  nAGQ=0, family=Gamma, data = data2[complete.cases(data2),])


glmm.gamma.sum <- summary(dep.glmm.gamma)
AIC(dep.glmm.gamma)
#r.squaredGLMM(dep.glmm.gamma)
glmm.gamma.preds <- predict(dep.glmm.gamma, type='response')
glmm.gamma.preds <- glmm.gamma.preds[which(glmm.gamma.preds<100)]
pdf("../plots/glmm_gamma_densities.pdf")
compare_densities_plot(glmm.gamma.preds, data2$y, "SF.12")
dev.off()

```

```{r}
with(mice_set, lmer(SF.12  ~  factor(sex) + 
               factor(ethnicity) + 
               age + 
               factor(education_state) + 
               factor(labour_state) + 
               factor(job_sec) + 
               gross_hh_income +  
                (1|pidp)))
```